export const Pages = {
  SIGNUP: "SIGNUP",
  SIGNUP_VERIFY: "SIGNUP_VERIFY",
  SIGNUP_COMPLETE: "SIGNUP_COMPLETE",
  CONSENT_LOCATION: "CONSENT_LOCATION",
  CONSENT_NOTIFICATION: "CONSENT_NOTIFICATION",
  HOME: "HOME",
  MESSAGE_DETAILS: "MESSAGE_DETAILS",
  SYMPTOM_SURVEY: "SYMPTOM_SURVEY",
  SURVEY_COMPLETE: "SURVEY_COMPLETE",
  ALERT_NOTIFICATION: "ALERT_NOTIFICATION",

  // TODO: hide these debug pages in release builds
  DEBUG_MENU: "DEBUG_MENU",
};
